# -*- encoding: utf-8 -*-
"""A staged brand, if present, must match its source.

release/<brand>/ is gitignored and regenerated by brand_apply — CI always rebuilds it,
so a shipped app cannot be stale. A DEVELOPER's copy can be, and a local demo run
against a pre-change EGF is indistinguishable from a correct one. Absent is fine
(nothing staged yet); present-and-different is a real defect."""
import hashlib
import pathlib

import pytest

BRANDS = pathlib.Path("brands/usurance/egf")
STAGED = pathlib.Path("src/locksmith/release/usurance/egf")


def _digests(d):
    return {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(d.glob("*.json"))}


def test_a_staged_usurance_brand_matches_brands_source():
    if not STAGED.exists():
        pytest.skip("no staged brand on this machine; brand_apply has not been run")
    assert _digests(STAGED) == _digests(BRANDS), (
        "the staged brand differs from brands/usurance/egf — re-run "
        "`python scripts/brand_apply.py --brand usurance`. A local demo or devbuild "
        "reads the staged copy, not brands/.")
