# -*- encoding: utf-8 -*-
"""Build-time brand manifest reader.

Read by scripts/brand_apply.py and by the PyInstaller specs to resolve the
active brand's identity from brands/<brand>/brand.toml. The runtime app does
NOT use this module — it reads the generated brand.json via
locksmith.core.branding. Selection: $LOCKSMITH_BRAND (default 'locksmith').
"""
import os
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BRANDS_DIR = REPO_ROOT / "brands"
DEFAULT_BRAND = "locksmith"
FALLBACK_BRAND = "example"


def active_brand_id() -> str:
    return os.environ.get("LOCKSMITH_BRAND", DEFAULT_BRAND)


def load_brand_manifest(brand_id: str | None = None) -> dict:
    """Parse brands/<brand>/brand.toml; fall back to brands/example if absent."""
    bid = brand_id or active_brand_id()
    brand_dir = BRANDS_DIR / bid
    if not (brand_dir / "brand.toml").is_file():
        brand_dir = BRANDS_DIR / FALLBACK_BRAND
    manifest = tomllib.loads((brand_dir / "brand.toml").read_text(encoding="utf-8"))
    manifest["_dir"] = brand_dir
    return manifest


def _org_name(manifest: dict) -> str:
    return manifest.get("org", {}).get("name") or manifest["identity"]["org_domain"]


def runtime_brand_json(manifest: dict) -> dict:
    """The brand.json runtime subset consumed by locksmith.core.branding."""
    return {
        "id": manifest["brand"]["id"],
        "display_name": manifest["brand"]["display_name"],
        "tagline": manifest["brand"]["tagline"],
        "org_name": _org_name(manifest),
        "org_domain": manifest["identity"]["org_domain"],
        "website": manifest["urls"]["website"],
        "support": manifest["urls"]["support"],
        "appcast_macos_xml": manifest["urls"]["appcast_macos_xml"],
        "appcast_windows_xml": manifest["urls"]["appcast_windows_xml"],
        "theme": dict(manifest.get("theme", {})),
    }


def exe_name(manifest: dict) -> str:
    return manifest["brand"]["display_name"]


WIX_DIR = REPO_ROOT / "packaging" / "wix"
WXS_TEMPLATE_PATH = WIX_DIR / "Locksmith.wxs.in"
WXS_OUTPUT_PATH = WIX_DIR / "Locksmith.wxs"
DMG_LAYOUT_PATH = REPO_ROOT / "packaging" / "dmg" / "layout.json"


def render_wxs(manifest: dict, template_text: str) -> str:
    # Strip the template's own doc-header comment so it is neither
    # token-substituted nor emitted (keeps rendered .wxs == committed .wxs).
    template_text = re.sub(r"\n<!-- TEMPLATE:.*?-->\n", "\n", template_text, flags=re.S)
    name = manifest["brand"]["display_name"]
    tokens = {
        "@@NAME@@": name,
        "@@MANUFACTURER@@": manifest["brand"]["manufacturer"],
        "@@UPGRADE_CODE@@": manifest["identity"]["upgrade_code"],
        "@@URL_ABOUT@@": manifest["urls"]["website"],
        "@@URL_SUPPORT@@": manifest["urls"]["support"],
        "@@TAGLINE@@": manifest["brand"]["tagline"],
        "@@DATA_DIR@@": manifest["identity"]["data_dir"],
    }
    out = template_text
    for token, value in tokens.items():
        out = out.replace(token, value)
    return out


def render_dmg_layout(manifest: dict) -> dict:
    name = manifest["brand"]["display_name"]
    return {
        "_comment": "Generated by scripts/brand_apply.py from the active brand. "
                    "Coordinates in pixels, origin top-left.",
        "window": {"position": [200, 200], "size": [540, 380]},
        "icon_size": 96,
        "background": "background.png",
        "volume_name": name,
        "icons": [
            {"name": f"{name}.app", "pos": [140, 200]},
            {"name": "Applications", "pos": [400, 200],
             "type": "symlink", "target": "/Applications"},
        ],
    }


def _identity_value(field: str, brand_id: str | None = None) -> str:
    m = load_brand_manifest(brand_id)
    if field == "id":
        return m["brand"]["id"]
    if field == "display_name":
        return m["brand"]["display_name"]
    if field == "release_prefix":
        # Convention (single source of truth for CI + publisher): locksmith is
        # back-compatible `releases`; every other brand is namespaced.
        bid = m["brand"]["id"]
        return "releases" if bid == "locksmith" else f"{bid}/releases"
    if field == "appcast_prefix":
        # Namespace root for this brand's appcast (before /v1/ and /archive/).
        # locksmith keeps the back-compatible `appcast`; every other brand is
        # namespaced so its app polls its own feed, not another brand's.
        bid = m["brand"]["id"]
        return "appcast" if bid == "locksmith" else f"{bid}/appcast"
    if field == "website":
        return m["urls"]["website"]
    ident = m.get("identity", {})
    if field not in ident:
        raise KeyError(field)
    return ident[field]


def _main(argv: list[str]) -> int:
    # Minimal CLI for shell/PowerShell: `python -m brandlib id <field>`.
    if len(argv) == 3 and argv[1] == "id":
        try:
            print(_identity_value(argv[2]))
            return 0
        except KeyError:
            print(f"unknown brand identity field: {argv[2]}", file=sys.stderr)
            return 2
    print("usage: python -m brandlib id "
          "<display_name|artifact_prefix|bundle_id|data_dir|id|release_prefix|"
          "appcast_prefix|website>",
          file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv))


def macos_info_plist(manifest: dict, version: str) -> dict:
    name = manifest["brand"]["display_name"]
    return {
        "CFBundleName": name,
        "CFBundleDisplayName": name,
        "CFBundleIdentifier": manifest["identity"]["bundle_id"],
        "CFBundleVersion": version,
        "CFBundleShortVersionString": version,
        "CFBundleExecutable": name,
        "CFBundlePackageType": "APPL",
        "CFBundleSupportedPlatforms": ["MacOSX"],
        "CFBundleDevelopmentRegion": "en",
        "CFBundleInfoDictionaryVersion": "6.0",
        "LSMinimumSystemVersion": "13.0",
        "NSPrincipalClass": "NSApplication",
        "NSHighResolutionCapable": True,
        "SUFeedURL": manifest["urls"]["appcast_macos_xml"],
        "SUEnableInstallerLauncherService": True,
        "SUEnableAutomaticChecks": False,
        "SUEnableDownloaderService": False,
        "NSAppTransportSecurity": {
            "NSAllowsArbitraryLoads": False,
            "NSExceptionDomains": {},
        },
    }
