# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for macOS — produces dist/Locksmith.app.

Phase 2 of the deploy/update design. Bundles libsodium dylibs, the brand's
compiled asset bundle (release/assets.rcc), qtawesome icon fonts, and the
embedded publisher_anchor.json.

Version is read from pyproject.toml so we maintain a single source of truth
(spec §5.1, §5.5).
"""
from __future__ import annotations

import os
import sys
import tomllib
from pathlib import Path

import qtawesome  # noqa: F401  — bundling its data only; we don't call it here
from PyInstaller.utils.hooks import copy_metadata, collect_submodules

# ---- Resolve paths -------------------------------------------------------

# When invoked as ``pyinstaller packaging/Locksmith.macos.spec`` the CWD is
# the repo root. SPECPATH is provided by PyInstaller.
REPO_ROOT = Path(SPECPATH).resolve().parent  # noqa: F821 — SPECPATH injected

import sys as _sys
_sys.path.insert(0, str(REPO_ROOT / "packaging"))
import brandlib as _brandlib
_BRAND = _brandlib.load_brand_manifest()
_BRAND_NAME = _BRAND["brand"]["display_name"]

# Where scripts/brand_apply.py staged this brand's self-contained release
# bundle (assets.rcc, brand.json, publisher_anchor.json, deploy_config.json,
# AppIcon.icns, egf/). Must be built BEFORE this spec runs.
_RELEASE = _brandlib.brand_release_dir(_BRAND["brand"]["id"], REPO_ROOT)

# Sparkle.framework lives at packaging/macos/Sparkle.framework. The
# release CI step "Fetch Sparkle framework" downloads it from
# https://github.com/sparkle-project/Sparkle/releases (2.x line) and
# extracts it there before invoking PyInstaller. KERI is the sole trust
# mechanism (spec §3); Sparkle's native EdDSA verification is OFF — see
# the omission of SUPublicEDKey in info_plist below.
SPARKLE_FRAMEWORK = REPO_ROOT / "packaging" / "macos" / "Sparkle.framework"

# ---- Read version --------------------------------------------------------

with (REPO_ROOT / "pyproject.toml").open("rb") as fh:
    _pyproject = tomllib.load(fh)
LOCKSMITH_VERSION = _pyproject["project"]["version"]

# ---- Discover qtawesome fonts directory ----------------------------------

import qtawesome as _qta_mod
_QTA_DIR = Path(_qta_mod.__file__).resolve().parent
_QTA_FONTS = _QTA_DIR / "fonts"

# ---- Datas: non-code resources bundled into the .app ---------------------

datas = [
    # Compiled brand resource bundle: the neutral assets/ pool verbatim plus
    # this brand's logo-slot files aliased onto the :/assets/custom/* paths
    # the UI expects (generate_qrc.py), registered at startup via
    # register_brand_resources(). Replaces the loose assets/ tree — every
    # runtime asset read now goes through :/ (Tasks 3-5); _asset_root() has
    # zero remaining disk-read callers.
    (str(_RELEASE / "assets.rcc"), "locksmith/release"),
    # Embedded KERI publisher trust anchor (Phase 2 placeholder, Phase 1 real)
    (str(_RELEASE / "publisher_anchor.json"), "locksmith/release"),
    # Deploy config (federation/CDN domains). Build-injected + gitignored like
    # the anchor; REQUIRED at runtime so the in-app verify gate can fetch the
    # real appcast/KEL — without it the gate falls back to example.com and the
    # KERI verify cannot run.
    (str(_RELEASE / "deploy_config.json"), "locksmith/release"),
    # Runtime brand identity (display name, theme, URLs). Generated by
    # brand_apply for the active brand; REQUIRED at runtime so the app renders
    # its OWN brand — without it branding.load_brand() finds no packaged file
    # and falls back to the baked-in Locksmith default (a non-locksmith brand
    # would show "Locksmith" in the window title/toolbar/theme).
    (str(_RELEASE / "brand.json"), "locksmith/release"),
    # qtawesome icon fonts (needed at runtime; not auto-collected reliably)
    (str(_QTA_FONTS), "qtawesome/fonts"),
    # User-facing release notes: the What's New dialog renders this version's
    # section after an update (locksmith.update.notes). Without it the modal
    # falls back to generic "see the notes online" copy.
    (str(REPO_ROOT / "CHANGELOG.md"), "locksmith"),
]

# Brand-bundled EGF docs — optional, only present when this brand ships one.
if (_RELEASE / "egf").is_dir():
    datas.append((str(_RELEASE / "egf"), "locksmith/release/egf"))

# Bundled entry-point plugins (e.g. KERI Foundation): discovered ONLY via
# importlib.metadata.entry_points(group="locksmith.plugins"). PyInstaller strips
# the Locksmith dist-info, so without copy_metadata that lookup returns an empty
# set and the plugin is INVISIBLE in a frozen app (works from source).
# See backlog/2026-07-09-kerifoundation-plugin-missing-in-frozen-builds.md.
datas += copy_metadata("Locksmith")

# Sparkle.framework: NOT added to PyInstaller's datas. PyInstaller's
# BUNDLE step nests data paths under Contents/Frameworks/, which would
# put the framework at Contents/Frameworks/Frameworks/Sparkle.framework
# AND PyInstaller's internal ad-hoc codesign chokes on a nested .framework
# subcomponent. build-macos.sh copies Sparkle.framework into
# Contents/Frameworks/ after PyInstaller exits, before the Developer ID
# codesign in scripts/sign.sh runs over the full bundle.
_ = SPARKLE_FRAMEWORK  # silence unused-variable check; build-macos.sh reads the path itself

# ---- Binaries: native libs ----------------------------------------------

binaries = [
    # libsodium — committed to repo root; loaded via custom loader in main.py
    (str(REPO_ROOT / "libsodium" / "libsodium.dylib"), "libsodium"),
    (str(REPO_ROOT / "libsodium" / "libsodium.26.x86_64.dylib"), "libsodium"),
    (str(REPO_ROOT / "libsodium" / "libsodium.23.arm.dylib"), "libsodium"),
]

# ---- Hidden imports ------------------------------------------------------
#
# Captured during initial spec authoring on a clean macOS-latest runner.
# Add to this list with a one-line comment ONLY when a runtime ImportError
# proves the dependency is needed. Do not preemptively pad.
hiddenimports = [
    # PySide6 plugin scan misses these on some 6.10.x builds:
    "PySide6.QtPrintSupport",
    "PySide6.QtSvg",
    "PySide6.QtNetwork",
    # qasync needs explicit hint when frozen:
    "qasync",
    # keripy uses dynamic imports for codec modules:
    "keri.core.coring",
    "keri.core.eventing",
    "keri.db.basing",
]

# Bundled entry-point plugins (kerifoundation, hoa_shell, actuary,
# product_designer, carrier) are reached only via entry-point ep.load() at
# runtime, so PyInstaller's static analysis never sees them — pull the whole
# locksmith.plugins tree in explicitly (paired with the copy_metadata above) so
# every current AND future [project.entry-points."locksmith.plugins"] entry
# resolves in the frozen app. Scoping to just kerifoundation left the HOA
# plugins (hoa_shell/actuary/product_designer) out, so the Usurance brand fell
# back to the vanilla vault picker instead of the peeled HOA roles surface.
hiddenimports += collect_submodules("locksmith.plugins")

block_cipher = None

# ---- Analysis ------------------------------------------------------------

a = Analysis(
    # Absolute path: PyInstaller resolves Analysis script paths relative
    # to SPECPATH, not CWD, so a relative "src/..." would look inside
    # packaging/ and fail.
    [str(REPO_ROOT / "src" / "locksmith" / "main.py")],
    pathex=[str(REPO_ROOT / "src")],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Slim the bundle — keep tkinter out (we use PySide6)
        "tkinter",
        # No tests in the artifact
        "pytest",
        "unittest",
    ],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# PyInstaller's Splash() is Tcl/Tk-based and explicitly unsupported on
# macOS (recent macOS dropped system Tcl/Tk). The Dock bounce already
# provides launch feedback, so the .app skips the splash; Windows has
# its own Splash() resource in Locksmith.windows.spec where it does work.

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=_BRAND_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,        # never UPX-compress signed binaries
    console=False,    # GUI app — no terminal window
    target_arch=None, # universal2 controlled by build script env
    codesign_identity=None,  # codesign happens in build-macos.sh, not here
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name=_BRAND_NAME,
)

app = BUNDLE(
    coll,
    name=f"{_BRAND_NAME}.app",
    icon=str(_RELEASE / "AppIcon.icns")
        if (_RELEASE / "AppIcon.icns").exists()
        else None,
    bundle_identifier=_BRAND["identity"]["bundle_id"],
    version=LOCKSMITH_VERSION,
    info_plist=_brandlib.macos_info_plist(_BRAND, LOCKSMITH_VERSION),
)
