# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Windows — produces dist/Locksmith/Locksmith.exe.

Phase 3 of the deploy/update design. Bundles libsodium.dll, the brand's
compiled asset bundle (release/assets.rcc), qtawesome icon fonts, and the
embedded publisher_anchor.json.

Version is read from pyproject.toml so we maintain a single source of truth
(spec §5.1, §5.5).

Layout:
    dist/Locksmith/Locksmith.exe                    (entry exe; no console)
    dist/Locksmith/_internal/                       (PySide6/Qt/qtawesome/keri deps)
    dist/Locksmith/_internal/libsodium.dll
    dist/Locksmith/_internal/locksmith/release/assets.rcc
"""
from __future__ import annotations

import os
import sys
import tomllib
from pathlib import Path

import qtawesome  # noqa: F401 — bundling its data only
from PyInstaller.utils.hooks import copy_metadata, collect_submodules

# ---- Resolve paths -------------------------------------------------------
# Use SPECPATH-relative absolute paths: PyInstaller resolves Analysis script
# paths relative to SPECPATH (not CWD), so any "src/..." relative would look
# inside packaging/ and fail.
REPO_ROOT = Path(SPECPATH).resolve().parent  # noqa: F821 — SPECPATH injected
SRC_ROOT = REPO_ROOT / "src"

import sys as _sys
_sys.path.insert(0, str(REPO_ROOT / "packaging"))
import brandlib as _brandlib
_BRAND = _brandlib.load_brand_manifest()
_BRAND_NAME = _BRAND["brand"]["display_name"]

# Where scripts/brand_apply.py staged this brand's self-contained release
# bundle (assets.rcc, brand.json, publisher_anchor.json, deploy_config.json,
# AppIcon.ico, egf/). Must be built BEFORE this spec runs.
_RELEASE = _brandlib.brand_release_dir(_BRAND["brand"]["id"], REPO_ROOT)
WIN_ICON = _RELEASE / "AppIcon.ico"

# ---- Read version --------------------------------------------------------

with (REPO_ROOT / "pyproject.toml").open("rb") as fh:
    _pyproject = tomllib.load(fh)
LOCKSMITH_VERSION = _pyproject["project"]["version"]
LOCKSMITH_RELEASE_CHANNEL = os.environ.get("LOCKSMITH_RELEASE_CHANNEL", "stable")

# ---- Discover qtawesome fonts directory ----------------------------------

import qtawesome as _qta_mod
_QTA_DIR = Path(_qta_mod.__file__).resolve().parent
_QTA_FONTS = _QTA_DIR / "fonts"

# ---- Datas: non-code resources bundled into the dist tree ----------------

datas = [
    # Compiled brand resource bundle: the neutral assets/ pool verbatim plus
    # this brand's logo-slot files aliased onto the :/assets/custom/* paths
    # the UI expects (generate_qrc.py), registered at startup via
    # register_brand_resources(). Replaces the loose assets/ tree — every
    # runtime asset read now goes through :/ (Tasks 3-5); _asset_root() has
    # zero remaining disk-read callers.
    (str(_RELEASE / "assets.rcc"), "locksmith/release"),
    # Embedded KERI publisher trust anchor (Phase 1 placeholder/real)
    (str(_RELEASE / "publisher_anchor.json"), "locksmith/release"),
    # Deploy config (federation/CDN domains). Build-injected + gitignored like
    # the anchor; REQUIRED at runtime so the in-app verify gate can fetch the
    # real appcast/KEL — without it the gate falls back to example.com and the
    # KERI verify cannot run.
    (str(_RELEASE / "deploy_config.json"), "locksmith/release"),
    # Runtime brand identity (display name, theme, URLs). Generated by
    # brand_apply for the active brand; REQUIRED at runtime so the app renders
    # its OWN brand — without it branding.load_brand() finds no packaged file
    # and falls back to the baked-in Locksmith default (a non-locksmith brand
    # would show "Locksmith" in the window title/toolbar/theme).
    (str(_RELEASE / "brand.json"), "locksmith/release"),
    # qtawesome icon fonts (needed at runtime; not auto-collected reliably)
    (str(_QTA_FONTS), "qtawesome/fonts"),
]

# Brand-bundled EGF docs — optional, only present when this brand ships one.
if (_RELEASE / "egf").is_dir():
    datas.append((str(_RELEASE / "egf"), "locksmith/release/egf"))

# Bundled entry-point plugins (e.g. KERI Foundation): discovered ONLY via
# importlib.metadata.entry_points(group="locksmith.plugins"). PyInstaller strips
# the Locksmith dist-info, so without copy_metadata that lookup returns an empty
# set and the plugin is INVISIBLE in a frozen app (works from source).
# See backlog/2026-07-09-kerifoundation-plugin-missing-in-frozen-builds.md.
datas += copy_metadata("Locksmith")

# ---- Binaries: native libs ----------------------------------------------
# libsodium.dll is installed via choco in CI and copied into packaging/windows/
# before pyinstaller runs (see build-windows.ps1 / release.ci.yml). The
# bootstrap loader in src/locksmith/main.py points pysodium at this DLL via
# ctypes.util.find_library monkey-patch.
binaries = []
_SODIUM_DLL = REPO_ROOT / "packaging" / "windows" / "libsodium.dll"
if _SODIUM_DLL.is_file():
    # Place at root of bundle so the loader's first candidate path resolves.
    binaries.append((str(_SODIUM_DLL), "."))
else:
    print(f"[spec] WARNING: {_SODIUM_DLL} not present; build will fail at runtime "
          "without a bundled libsodium.dll. CI's 'Stage libsodium for PyInstaller' "
          "step copies it into place before pyinstaller runs.")

# WinSparkle.dll — bundled next to Locksmith.exe so the ctypes loader in
# locksmith.update.winsparkle_bridge finds it as `WinSparkle.dll`. The
# release CI step "Fetch WinSparkle" downloads it from
# https://github.com/vslavik/winsparkle/releases (0.8+ line) into
# packaging/windows/winsparkle/ before invoking PyInstaller.
#
# Runtime appcast URL: https://releases.keri.host/appcast/v1/windows.xml
# (brand-derived by winsparkle_init._appcast_url via win_sparkle_set_appcast_url).
# WinSparkle's native DSA verification is DISABLED at runtime
# (win_sparkle_set_dsa_pub_pem(NULL)) — KERI is sole trust (spec §3).
_WINSPARKLE_DLL = REPO_ROOT / "packaging" / "windows" / "winsparkle" / "WinSparkle.dll"
if _WINSPARKLE_DLL.is_file():
    binaries.append((str(_WINSPARKLE_DLL), "."))
else:
    print(f"[spec] WARNING: {_WINSPARKLE_DLL} not present; bundle will ship "
          "without in-app updates. CI's 'Fetch WinSparkle' step copies "
          "WinSparkle.dll into place before pyinstaller runs.")

# ---- Hidden imports ------------------------------------------------------
#
# Mirror the macOS spec's pinned list. Add to this list with a one-line
# comment ONLY when a runtime ImportError proves the dependency is needed.
hiddenimports = [
    # PySide6 plugin scan misses these on some 6.10.x builds:
    "PySide6.QtPrintSupport",
    "PySide6.QtSvg",
    "PySide6.QtNetwork",
    # qasync needs explicit hint when frozen:
    "qasync",
    # keripy uses dynamic imports for codec modules:
    "keri.core.coring",
    "keri.core.eventing",
    "keri.db.basing",
]

# Bundled entry-point plugins (kerifoundation, hoa_shell, actuary,
# product_designer, carrier) are reached only via entry-point ep.load() at
# runtime, so PyInstaller's static analysis never sees them — pull the whole
# locksmith.plugins tree in explicitly (paired with the copy_metadata above) so
# every current AND future [project.entry-points."locksmith.plugins"] entry
# resolves in the frozen app. Scoping to just kerifoundation left the HOA
# plugins (hoa_shell/actuary/product_designer) out, so the Usurance brand fell
# back to the vanilla vault picker instead of the peeled HOA roles surface.
hiddenimports += collect_submodules("locksmith.plugins")

block_cipher = None

# ---- Analysis ------------------------------------------------------------

a = Analysis(
    [str(SRC_ROOT / "locksmith" / "main.py")],
    pathex=[str(SRC_ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Slim the bundle — keep tkinter out (we use PySide6)
        "tkinter",
        # No tests in the artifact
        "pytest",
        "unittest",
    ],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# NOTE: no PyInstaller Splash() here. Its Tcl/Tk splash can't run inside a macOS
# .app (so the splash was absent there) and DPI-rescales on Windows (the splash
# "moves and shrinks"). The app now shows a Qt QSplashScreen from main.py
# (_make_splash) on every platform — DPI-correct and consistent. SplashScreen.png
# ships inside the bundled assets.rcc (:/assets/custom/SplashScreen.png), which
# main.py loads via the registered brand resources at runtime.

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=_BRAND_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,           # UPX-compressed binaries fail Authenticode signing
    console=False,       # GUI app — no terminal window flash
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(WIN_ICON) if WIN_ICON.is_file() else None,
    version_file=None,   # MSI carries the version metadata
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name=_BRAND_NAME,
)
