"""Activate the usurance brand for every test in this package.

`egf_local_dir()` returns None until `brand()` has run -- it reads
`_brand_source_dir`, which `load_brand()` populates as a side effect. And the
release bundle it points at is GITIGNORED (`.gitignore:244`), generated by
`scripts/brand_apply.py`, so a fresh clone has no usurance brand at all. Both
halves are handled here: build if absent, then activate.

Mirrors tests/conftest.py's `_build_default_bundle` / `default_brand_resources`
pair, including resetting the branding cache on BOTH sides -- an activated brand
that outlives its test leaks into every later module in the session.
"""
import importlib
import sys
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[3]
_BRAND = "usurance"


def _release_dir() -> Path:
    for extra in (_REPO / "scripts", _REPO / "packaging"):
        if str(extra) not in sys.path:
            sys.path.insert(0, str(extra))
    brandlib = importlib.import_module("brandlib")
    out = brandlib.brand_release_dir(_BRAND, _REPO)
    if not (out / "brand.json").is_file():
        importlib.import_module("brand_apply").apply(
            _BRAND, _REPO, out=out, check=False)
    return out


@pytest.fixture(autouse=True)
def usurance_brand(monkeypatch):
    from locksmith.core import branding

    out = _release_dir()
    brand_json = out / "brand.json"
    assert brand_json.is_file(), (
        f"brand_apply did not produce {brand_json}; the CUO form's tests cannot "
        f"run without the usurance brand's EGF bundle")

    monkeypatch.setenv(branding.BRAND_CONFIG_ENV_VAR, str(brand_json))
    branding._reset_cache_for_tests()
    branding.brand()                      # populates _brand_source_dir
    # REGISTER the compiled resources too, not just activate the brand. Without
    # this every `:/assets/...` path resolves to nothing and Qt hands back a NULL
    # QIcon SILENTLY -- so an icon-only button renders blank and any test that
    # asserted on the icon path string would still pass. Measured: the parse
    # directory's browse button had `icon().isNull() is True` under this fixture
    # while it drew correctly in the running app, which registers them.
    branding.register_brand_resources()
    yield
    branding._reset_cache_for_tests()     # also unregisters
